version: 2

conda:
    environment: environment.yml
python:
    version: 3
    install:
       - requirements: requirements.txt
       - method: pip
         path: .
       - method: setuptools
         path: .
