language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install --upgrade pytest
# command to run tests
script:
  - python -m examples.quickstart
  - python -m pytest test

