sudo: true
language: python
python:
  - "3.6"
# command to install dependencies
addons:
  apt:
    packages:
    - redis-server
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install --upgrade pytest
# command to run tests
script:
  - python -m examples.quickstart
  - travis_wait python -m pytest test

