sudo: true
language: python
python:
  - "3.6"
# command to install dependencies
addons:
  apt:
    sources:
    - sourceline: 'deb http://cran.rstudio.com/bin/linux/ubuntu trusty/'
    packages:
    - redis-server
    - r-base
    - r-base-dev
    - r-base-core
    - r-recommended
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install --upgrade pytest
# command to run tests
script:
  - travis_wait python -m pytest test
