sudo: true
language: python
python:
  - "3.6"
# command to install dependencies
addons:
  apt:
    sources:
    - sourceline: 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
    packages:
    - redis-server
    - r-base
    - r-base-dev
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install --upgrade pytest
# command to run tests
script:
  - travis_wait python -m pytest test
