name: py35
dependencies:
  - python=3.5
  - numpy
  - scipy
  - bokeh
  - pandas
  - flask
  - scikit-learn
  - distributed
  - matplotlib
  - sphinx
  - pandoc
  - nbconvert
  - ipykernel
  - r
  - pip:
    - nbsphinx
